### ISSUE TITLE
ImportError when using complex numbers

### ISSUE THREAD

**Issue by pierricmora** [jorgensd/dolfinx_mpc#50]
Hi again,
I'd like to use dolfinx_mpc with complex numbers. However,

```bash
docker run --rm -ti  ghcr.io/jorgensd/dolfinx_mpc:v0.6.1.post0
source /usr/local/bin/dolfinx-complex-mode

python3
import dolfinx_mpc
```
raises
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/dolfinx_mpc/__init__.py", line 10, in <module>
    import dolfinx_mpc.cpp
ImportError: /usr/local/lib/libdolfinx_mpc.so.0.5: undefined symbol: _ZN7dolfinx2la5petsc18create_vector_wrapERKNS_6common8IndexMapEiSt4spanIKdLm18446744073709551615EE
```

When I manually compile dolfinx_mpc atop a dolfinx/dolfinx:latest docker image the error is almost identical (only the version number of libdolfinx_mpc.so changes):
```bash
ImportError: /usr/local/lib/libdolfinx_mpc.so.0.6: undefined symbol: _ZN7dolfinx2la5petsc18create_vector_wrapERKNS_6common8IndexMapEiSt4spanIKdLm18446744073709551615EE
```

**Comment by jorgensd** [comment]
@pierricmora could you try the following image: `ghcr.io/jorgensd/dolfinx_mpc:dokken-complex_docker`.
If it works, I'll publish a new release based on it
