### ISSUE TITLE
AttributeError: 'MultiPointConstraint' object has no attribute 'create_contact_slip_condition'

### ISSUE THREAD

**Issue by jkrokowski** [jorgensd/dolfinx_mpc#7]
When I try to run the demo_contact_2D.py, I get one line of calcuations (like so):
`2021-11-08 22:10:37.453 (   1.221s) [main            ]                log.cpp:45    INFO| Run theta:1.05, Quad: False, Gmsh False, Res 1.00e-01`

followed by this error
```
Traceback (most recent call last):
  File "demo_contact_2D.py", line 236, in <module>
    demo_stacked_cubes(outfile, theta=theta, gmsh=gmsh,
  File "demo_contact_2D.py", line 99, in demo_stacked_cubes
    mpc.create_contact_slip_condition(mt, 4, 9, nh)
AttributeError: 'MultiPointConstraint' object has no attribute 'create_contact_slip_condition'
```

**Comment by jorgensd** [comment]
Which version of `dolfinx_mpc` are you running?
Currently the `master` branch is broken due to some changes to `dolfinx` that happened today. However, if you use the dolfinx main branch from https://github.com/FEniCS/dolfinx/commit/8fcc3763785f5066490d713583494dbfd1cb4e4d everything should run

**Comment by jkrokowski** [comment]
I have had this issue using the docker image from the github repo. That 
should all be self contained, correct?

**Comment by jorgensd** [comment]
The docker image has not been updated for quite a while. It runs version 0.1.0, which matches: https://github.com/jorgensd/dolfinx_mpc/releases/tag/0.1.0, so then you should do `git checkout 0.1.0` on the cloned repository.

I can make a 0.3.0 docker image in one of the coming days.

**Comment by jorgensd** [comment]
You can either try the following Dockerfile:
```
FROM dolfinx/dev-env as dolfinx-mpc
WORKDIR /tmp
# Set env variables
ENV PETSC_ARCH="linux-gnu-real-32"\
    HDF5_MPI="ON" \
    CC=mpicc \
    HDF5_DIR="/usr/lib/x86_64-linux-gnu/hdf5/mpich/" \
    XTENSOR_VERSION="0.23.10" \
    XTENSOR_BLAS_VERSION="0.19.1" \
    DOLFINX_VERSION="v0.3.0" \
    XTL_VERSION="0.7.2"


RUN git clone -b ${XTL_VERSION} --single-branch https://github.com/xtensor-stack/xtl.git &&     cd xtl &&     cmake -G Ninja . &&     ninja install &&     cd ../ &&     git clone -b ${XTENSOR_VERSION} --single-branch https://github.com/xtensor-stack/xtensor.git &&     cd xtensor &&     cmake -G Ninja . &&     ninja install &&     cd ../ &&     git clone -b ${XTENSOR_BLAS_VERSION} --single-branch https://github.com/xtensor-stack/xtensor-blas.git &&     cd xtensor-blas &&     cmake -G Ninja . &&     ninja install &&  cd .. && rm -rf xtl xtensor xtensor-blas
RUN git clone -b ${DOLFINX_VERSION} --single-branch https://github.com/FEniCS/basix.git && cd basix && cmake -G Ninja -DCMAKE_BUILD_TYPE="Release" -B build-dir -S . &&   cmake --build build-dir &&     cmake --install build-dir &&     python3 -m pip install ./python && cd ..
RUN python3 -m pip install git+https://github.com/FEniCS/ufl.git
RUN python3 -m pip install git+https://github.com/FEniCS/ffcx.git@${DOLFINX_VERSION}
RUN git clone -b ${DOLFINX_VERSION} --single-branch https://github.com/FEniCS/dolfinx.git && cd  dolfinx && cmake -G Ninja -DCMAKE_BUILD_TYPE="Release" -B build-dir -S ./cpp &&   cmake --build build-dir &&     cmake --install build-dir &&     python3 -m pip install ./python && cd ..

# Install dolfinx_mpc
RUN  git clone https://github.com/jorgensd/dolfinx_mpc.git  && \
    cd dolfinx_mpc && \
    git checkout 88fe1175d477bf4f65c09ec7c74477f12797d5b8 && \
    cmake -G Ninja -DCMAKE_BUILD_TYPE=Developer -B build-dir cpp/ && \
    ninja install -j3  -C build-dir && \
    pip3 install python/. --upgrade
# Install h5py
RUN pip3 install --no-binary=h5py h5py

WORKDIR /root
```
which is compatible with the commit `88fe1175d477bf4f65c09ec7c74477f12797d5b8` matching the dolfinx v0.3.0 release.

I am also putting a docker image at [DockerHub](https://hub.docker.com/repository/docker/dokken92/dolfinx_mpc) (currently uploading) under the tag `dokken92/dolfinx_mpc:v0.3.0`.

**Comment by jorgensd** [comment]
I'll close this issue, as I've pushed a tag and a docker image that can be used
